### ISSUE TITLE
bgp: router id insufficient discriminator for route-refresh stale marking

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/maghemite#241]
This is a follow up for this review comment

- https://github.com/oxidecomputer/maghemite/pull/199/files#r1585208765

We need to mark routes as stale for route refresh based on session, not on router id, as we may have multiple sessions with a single router and thus single router id.

**Comment by taspelund** [comment]
This discriminator should be something specific to the BGP session, since that should have a 1:1 mapping to a configured peer.
I did an initial code-dive to see what value might make sense to use in our BGP implementation, and it seems like `Cnx: BgpConnection` is the likely candidate. A tuple of local/remote sockaddrs might also be an option here, but that just seems like peeling one layer of abstraction off of the `BgpConnection` trait without an immediately obvious upside.
